### ISSUE TITLE
Exception: No RegionEndpoint or ServiceURL configured

### ISSUE THREAD

**Issue by OlegBoulanov** [OlegBoulanov/s3i#2]
Can be fixed by setting _region = us-east-1_ in **.aws/credentials** file
Actual fix would require implementing AWS S3 client map

**Comment by OlegBoulanov** [comment]
> 
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Amazon.Runtime.AmazonClientException: No RegionEndpoint or ServiceURL configured
   at Amazon.Runtime.ClientConfig.Validate()
   at Amazon.S3.AmazonS3Config.Validate()
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
   at s3i_lib.S3Helper..ctor(String profileName)
   at s3i.Program.<__Main>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at s3i.Program.Main(String[] args)

**Comment by OlegBoulanov** [comment]
fixed in 1.0.42
